---
abstract: 'Leet speak by Japanese gals'
author:
  - 'Naoki Tomita <tomita@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-Gal
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  File::ShareDir: 1.00
  Unicode::Japanese: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
